FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Source code is mounted via volume in docker-compose.dev.yml
# COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
